### ISSUE TITLE
Why do the instructions start with "If you are a doctor"

### ISSUE THREAD

**Issue by mahlernim** [Kent0n-Li/ChatDoctor#10]
Thank you for your interesting work.
In the `chatdoctor5k.json` and `chatdoctor200k.json` I see that the instructions start with "If you are a doctor".
I am curious why the instructions do not start with "You are a doctor".
Is this a common way to perform the alpaca instruction fine-tuning?

**Comment by Kent0n-Li** [comment]
They should not have a major impact on the outcome and both should be acceptable.

**Comment by mahlernim** [comment]
I understood as the fine-tuning process should only influence the model in the context of when the model is acting as a doctor.
So the "major imapct" implies that the fine-tuning should not have impact when the model is not acting as a doctor.
Did I get it right?

**Comment by Kent0n-Li** [comment]
Yes, if the patient's description is used as an instruction instead of an input, the trained model will affect the conversational ability of other tasks, while fixing the instruction as 'if you are a doctor' and adding this instruction to the inference will ensure the proper operation of the model.

**Comment by mahlernim** [comment]
Well understood. Thank you so much for the clarification!
